name: test

on:
  workflow_dispatch:
    inputs:
      service_name:
        required: true
        type: choice
        description: "test"
        options:
        - casino
        - not_casino
  # schedule:
  #   # Regularly run the action at midnight on Saturday
  #   - cron: '*/3 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: check input
        run: echo ${{ inputs.service_name }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out repository code (Casino)
        if: ${{ inputs.service_name  == 'casino' }}
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: main_repo
          clean: false
      - name: run ls
        run: ls
