name: first CI TEST

on:
- pull_request_target

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: check input
        run: echo ${{ inputs.service_name }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out repository code (Casino)
        if: ${{ inputs.service_name  == 'casino' }}
        run:
          git fetch && git checkout origin/main -- main_repo
      - name: run ls
        run: ls
