name: test

on:
  workflow_dispatch:
  # schedule:
  #   # Regularly run the action at midnight on Saturday
  #   - cron: '*/3 * * * *'
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      template_dir:
        required: false
        type: string
        default: ""
        description: "(For kubernetes-manifests) a path to a directory containing 'kustomization.yaml'"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Run shell
        run: |
          echo ${{ inputs.template_dir }}
