name: test

on:
  workflow_dispatch:
  schedule:
    # Regularly run the action at midnight on Saturday
    - cron: '*/3 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
